lane :test_bump_version_update_changelog_create_pr do |options|
  bump_version_update_changelog_create_pr(
    current_version: 'current_version_number',
    changelog_latest_path: './path-to/CHANGELOG.latest.md',
    changelog_path: './path-to/CHANGELOG.md',
    files_to_update: ['./file-containing-version-1.txt', './file-containing-version-2.rb'],
    files_to_update_without_prerelease_modifiers: [],
    repo_name: 'repo-name',
    github_pr_token: 'github-api-token', # This can also be obtained from ENV GITHUB_PULL_REQUEST_API_TOKEN
    github_token: 'github-token',
    github_rate_limit: 0,
    branch: 'main',
    editor: 'vim'
  )
end

lane :test_replace_version_number do |options|
  replace_version_number(
    current_version: 'current_version_number',
    new_version_number: 'new_version_number',
    files_to_update: ['./file-containing-version-1.txt', './file-containing-version-2.rb'],
    files_to_update_without_prerelease_modifiers: []
  )
end
